# -*- coding: utf-8 -*-
"""DL_Expt7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bHIyQN0YUiiAslHaoVMuTwDFfgR3oUCs
"""

import torch
import torchvision
import torchvision.transforms as transforms
from torchvision import datasets
from torch.utils.data import DataLoader

print("Imported torch, torchvision, and DataLoader.")

# 2. Define a transformation pipeline
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

print("Defined image transformation pipeline.")

# 3. Load the CIFAR-100 training dataset
batch_size = 64
data_root = './data'

train_dataset = datasets.CIFAR100(root=data_root, train=True, download=True, transform=transform)

print(f"Loaded CIFAR-100 training dataset with {len(train_dataset)} samples.")

# 4. Create a DataLoader for the training dataset
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

print(f"Created DataLoader for training with batch size {batch_size}.")
print("Preprocessing steps completed successfully for CIFAR-100 training data.")

import torch.nn as nn

# Latent dimension for the generator
latent_dim = 100
# Image dimensions for CIFAR-100 (3 channels, 32x32 pixels)
img_channels = 3
img_size = 32

# Define the Generator Network
class Generator(nn.Module):
    def __init__(self, latent_dim, img_channels, img_size):
        super(Generator, self).__init__()
        self.img_size = img_size

        self.main = nn.Sequential(
            # Input: latent_dim vector
            nn.Linear(latent_dim, 256 * (img_size // 8) * (img_size // 8)),
            nn.BatchNorm1d(256 * (img_size // 8) * (img_size // 8)),
            nn.ReLU(True),
            nn.Unflatten(1, (256, img_size // 8, img_size // 8)), # Reshape to 256x4x4 (for 32x32 images)

            nn.ConvTranspose2d(256, 128, 4, 2, 1, bias=False), # Output: 128x8x8
            nn.BatchNorm2d(128),
            nn.ReLU(True),

            nn.ConvTranspose2d(128, 64, 4, 2, 1, bias=False), # Output: 64x16x16
            nn.BatchNorm2d(64),
            nn.ReLU(True),

            nn.ConvTranspose2d(64, img_channels, 4, 2, 1, bias=False), # Output: img_channels x 32x32
            nn.Tanh() # Output pixel values in [-1, 1]
        )

    def forward(self, z):
        img = self.main(z)
        return img

# Define the Discriminator Network
class Discriminator(nn.Module):
    def __init__(self, img_channels, img_size):
        super(Discriminator, self).__init__()
        self.img_size = img_size

        self.main = nn.Sequential(
            # Input: img_channels x img_size x img_size
            nn.Conv2d(img_channels, 64, 4, 2, 1, bias=False), # Output: 64 x (img_size/2) x (img_size/2)
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(64, 128, 4, 2, 1, bias=False), # Output: 128 x (img_size/4) x (img_size/4)
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(128, 256, 4, 2, 1, bias=False), # Output: 256 x (img_size/8) x (img_size/8)
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Flatten(),
            nn.Linear(256 * (img_size // 8) * (img_size // 8), 1),
            nn.Sigmoid() # Output a single probability (real/fake)
        )

    def forward(self, img):
        validity = self.main(img)
        return validity

print("Defined Generator and Discriminator models.")

# Optional: Instantiate models to verify architecture
gen = Generator(latent_dim, img_channels, img_size)
disc = Discriminator(img_channels, img_size)

print(f"Generator model: {gen}")
print(f"Discriminator model: {disc}")

import torch.optim as optim

# Check if CUDA is available and set the device accordingly
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Move models to the device
gen = gen.to(device)
disc = disc.to(device)

# 1. Define the loss function (Binary Cross-Entropy Loss)
criterion = nn.BCELoss()

print("Defined BCELoss as the adversarial loss function.")

# Learning rate for optimizers
lr = 0.0002
# Beta1 hyperparameter for Adam optimizers
beta1 = 0.5

# 2. Initialize optimizers for Generator and Discriminator
optimizer_g = optim.Adam(gen.parameters(), lr=lr, betas=(beta1, 0.999))
optimizer_d = optim.Adam(disc.parameters(), lr=lr, betas=(beta1, 0.999))

print(f"Initialized Adam optimizer for Generator with lr={lr}, beta1={beta1}.")
print(f"Initialized Adam optimizer for Discriminator with lr={lr}, beta1={beta1}.")
print("Loss functions and optimizers configured successfully.")

import torchvision.utils as vutils
import numpy as np
import time # Import the time module

# 1. Set up training parameters
num_epochs = 50

# Fixed noise for visualization
fixed_noise = torch.randn(64, latent_dim, device=device)

# Lists to keep track of progress
g_losses = []
d_losses = []
img_list = []

print("Starting GAN training loop...")

# Record the start time
start_time = time.time()

for epoch in range(num_epochs):
    for i, data in enumerate(train_loader, 0):
        # 3. Train the Discriminator
        disc.zero_grad()
        # Format batch
        real_cpu = data[0].to(device)
        b_size = real_cpu.size(0)
        label = torch.full((b_size,), 1.0, dtype=torch.float, device=device) # Real labels

        # Forward pass real batch through Discriminator
        output = disc(real_cpu).view(-1)
        # Calculate loss on all-real batch
        errD_real = criterion(output, label)
        # Calculate gradients for D in backward pass
        errD_real.backward()
        D_x = output.mean().item()

        # Generate fake image batch with Generator
        noise = torch.randn(b_size, latent_dim, device=device)
        fake = gen(noise)
        label.fill_(0.0) # Fake labels

        # Classify all fake batch with Discriminator
        output = disc(fake.detach()).view(-1)
        # Calculate D's loss on the all-fake batch
        errD_fake = criterion(output, label)
        # Calculate the gradients for this batch
        errD_fake.backward()
        D_G_z1 = output.mean().item()
        # Add the gradients from the all-real and all-fake batches
        errD = errD_real + errD_fake
        # Update Discriminator
        optimizer_d.step()

        # 4. Train the Generator
        gen.zero_grad()
        label.fill_(1.0) # Generator wants fake images to be classified as real
        # Since we just updated D, perform another forward pass of all-fake batch through D
        output = disc(fake).view(-1)
        # Calculate G's loss based on this output
        errG = criterion(output, label)
        # Calculate gradients for G
        errG.backward()
        D_G_z2 = output.mean().item()
        # Update Generator
        optimizer_g.step()

        # Output training stats
        if i % 100 == 0 or i == len(train_loader) - 1:
            print(f'Epoch [{epoch}/{num_epochs}] Batch [{i}/{len(train_loader)}]	LossD: {errD.item():.4f}	LossG: {errG.item():.4f}	D(x): {D_x:.4f}	D(G(z)): {D_G_z1:.4f} / {D_G_z2:.4f}')

        # Save Losses for plotting later
        g_losses.append(errG.item())
        d_losses.append(errD.item())

        # Check how the generator is doing by saving G's output on fixed_noise
        if (i % 500 == 0) or ((epoch == num_epochs-1) and (i == len(train_loader)-1)):
            with torch.no_grad():
                fake = gen(fixed_noise).detach().cpu()
            img_list.append(vutils.make_grid(fake, padding=2, normalize=True))

print("GAN training loop completed.")

# Record the end time
end_time = time.time()
# Calculate total training time
total_training_time = end_time - start_time

# Print the total training time in a human-readable format
print(f"Total training time: {total_training_time:.2f} seconds")
print(f"Total training time: {total_training_time / 60:.2f} minutes")

import matplotlib.pyplot as plt
import numpy as np

# Select a few images from img_list to display progress
# For example, select images from the beginning, middle, and end of training
num_images_to_display = 6
indices_to_display = np.linspace(0, len(img_list) - 1, num_images_to_display, dtype=int)

plt.figure(figsize=(15, 10))
for i, idx in enumerate(indices_to_display):
    plt.subplot(2, 3, i + 1)
    # Convert tensor to numpy array and permute dimensions for matplotlib (C, H, W) -> (H, W, C)
    img = np.transpose(img_list[idx].cpu().numpy(), (1, 2, 0))
    plt.imshow(img)
    plt.title(f"Generated at Iteration {idx * 500}") # Assuming images are saved every 500 batches
    plt.axis('off')
plt.suptitle('Generated Images Over Training Progress', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

print("Displayed a selection of generated images from img_list.")

import matplotlib.pyplot as plt

# Create a new figure and axes object for the plot
plt.figure(figsize=(10, 5))

# Plot the Generator loss curve
plt.plot(g_losses, label='Generator Loss')

# Plot the Discriminator loss curve
plt.plot(d_losses, label='Discriminator Loss')

# Add a title to the plot
plt.title('Generator and Discriminator Loss During Training')

# Add labels for the axes
plt.xlabel('Iterations')
plt.ylabel('Loss')

# Include a legend
plt.legend()

# Display the plot
plt.grid(True)
plt.show()

print("Displayed Generator and Discriminator loss curves.")