# -*- coding: utf-8 -*-
"""DL_EXPT8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLSRYHEJLPuA1r6UEyguCwr7ZGHNlMk3
"""

# Install required libraries
!pip install transformers datasets kagglehub -q

import kagglehub
import os
import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
from torch.optim import AdamW
from transformers.optimization import get_scheduler
from sklearn.metrics import accuracy_score, classification_report
from tqdm import tqdm

# Download the AG News dataset from Kaggle
path = kagglehub.dataset_download("amananandrai/ag-news-classification-dataset")
print("Path to dataset files:", path)
print(os.listdir(path))

# Load train and test CSV files
train_df = pd.read_csv(os.path.join(path, "train.csv"))
test_df  = pd.read_csv(os.path.join(path, "test.csv"))

# The columns are now correctly read as "Class Index", "Title", "Description" from the CSV header.
# We need to rename them for consistency with the rest of the notebook.
train_df.rename(columns={"Class Index": "label", "Title": "title", "Description": "description"}, inplace=True)
test_df.rename(columns={"Class Index": "label", "Title": "title", "Description": "description"}, inplace=True)

# Combine title + description into a single text field
train_df["text"] = train_df["title"] + " " + train_df["description"]
test_df["text"]  = test_df["title"]  + " " + test_df["description"]

# Labels are 1-indexed; convert to 0-indexed for PyTorch
# After correcting the header, the 'label' column should contain numeric values.
train_df["label"] = train_df["label"] - 1
test_df["label"]  = test_df["label"]  - 1

print("Train size:", len(train_df))
print("Test size: ", len(test_df))
print("\nClass distribution:\n", train_df["label"].value_counts())
train_df.head(3)

# Use a small subset for faster training (increase for better accuracy)
TRAIN_SIZE = 4000   # samples per class
TEST_SIZE  = 400    # samples per class

train_df = train_df.groupby("label").apply(lambda x: x.sample(TRAIN_SIZE, random_state=42)).reset_index(drop=True)
test_df  = test_df.groupby("label").apply(lambda x: x.sample(TEST_SIZE,  random_state=42)).reset_index(drop=True)

print("Sampled train size:", len(train_df))
print("Sampled test size: ", len(test_df))

# Load the DistilBERT tokenizer
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

MAX_LEN = 128   # max token length per input

class NewsDataset(Dataset):
    """Custom PyTorch Dataset for tokenizing and batching news text."""

    def __init__(self, texts, labels, tokenizer, max_len):
        self.texts     = texts
        self.labels    = labels
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        # Tokenize the text: adds [CLS], [SEP], pads/truncates to max_len
        encoding = self.tokenizer(
            self.texts[idx],
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt"
        )
        return {
            "input_ids":      encoding["input_ids"].squeeze(0),       # token IDs
            "attention_mask": encoding["attention_mask"].squeeze(0),  # 1 = real token, 0 = padding
            "label":          torch.tensor(self.labels[idx], dtype=torch.long)
        }

# Create dataset objects
train_dataset = NewsDataset(train_df["text"].tolist(), train_df["label"].tolist(), tokenizer, MAX_LEN)
test_dataset  = NewsDataset(test_df["text"].tolist(),  test_df["label"].tolist(),  tokenizer, MAX_LEN)

# Create DataLoaders for batching
BATCH_SIZE = 32

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False)

print("Train batches:", len(train_loader))
print("Test batches: ", len(test_loader))

NUM_CLASSES = 4   # World, Sports, Business, Sci/Tech

# Load pre-trained DistilBERT with a classification head for 4 classes
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=NUM_CLASSES
)

# Move model to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model  = model.to(device)

print("Using device:", device)

EPOCHS    = 3
LR        = 2e-5   # standard learning rate for fine-tuning BERT models

# AdamW optimizer — standard choice for transformer fine-tuning
optimizer = AdamW(model.parameters(), lr=LR)

# Linear learning rate scheduler with warmup
total_steps = len(train_loader) * EPOCHS
scheduler   = get_scheduler(
    name="linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=total_steps
)

print(f"Total training steps: {total_steps}")

def train_epoch(model, loader, optimizer, scheduler, device):
    """Run one full pass over the training data."""
    model.train()
    total_loss = 0

    for batch in tqdm(loader, desc="Training"):
        input_ids      = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels         = batch["label"].to(device)

        # Forward pass — model returns loss + logits when labels are passed
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss    = outputs.loss

        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(loader)
    return avg_loss

def evaluate(model, loader, device):
    """Evaluate model on a given DataLoader; returns accuracy and predictions."""
    model.eval()
    all_preds  = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(loader, desc="Evaluating"):
            input_ids      = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels         = batch["label"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            preds   = torch.argmax(outputs.logits, dim=1)   # pick class with highest score

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    acc = accuracy_score(all_labels, all_preds)
    return acc, all_preds, all_labels

# Training loop
for epoch in range(1, EPOCHS + 1):
    print(f"\n--- Epoch {epoch}/{EPOCHS} ---")

    train_loss = train_epoch(model, train_loader, optimizer, scheduler, device)
    val_acc, _, _ = evaluate(model, test_loader, device)

    print(f"Train Loss: {train_loss:.4f} | Val Accuracy: {val_acc:.4f}")

# Class label names for the report
class_names = ["World", "Sports", "Business", "Sci/Tech"]

# Get final predictions on the test set
final_acc, preds, labels = evaluate(model, test_loader, device)

print(f"\nFinal Test Accuracy: {final_acc:.4f}")
print("\nClassification Report:")
print(classification_report(labels, preds, target_names=class_names))

def predict(text, model, tokenizer, device):
    """Predict the category of a single news article."""
    model.eval()

    # Tokenize the input text
    encoding = tokenizer(
        text,
        max_length=MAX_LEN,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    )

    input_ids      = encoding["input_ids"].to(device)
    attention_mask = encoding["attention_mask"].to(device)

    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        pred    = torch.argmax(outputs.logits, dim=1).item()

    return class_names[pred]


# Example predictions
samples = [
    "NASA launches new Mars rover to explore the surface of the red planet.",
    "Stock markets fell sharply as inflation data came in higher than expected.",
    "UN holds emergency meeting over ongoing conflict in the Middle East.",
    "India won the cricket world cup by 10 wickets"
]

for sample in samples:
    label = predict(sample, model, tokenizer, device)
    print(f"Text   : {sample[:70]}...")
    print(f"Predicted: {label}\n")