# -*- coding: utf-8 -*-
"""DL_Expt5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpLEJeyQY_P2HHqKas3D4Un7EGaCQPtN
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

data = pd.read_csv("spam.csv", encoding='latin-1')

data = data[['v1', 'v2']]
data.columns = ['label', 'text']

encoder = LabelEncoder()
data['label'] = encoder.fit_transform(data['label'])

X_train, X_test, y_train, y_test = train_test_split(
    data['text'], data['label'], test_size=0.2, random_state=42
)

vocab_size = 5000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

max_length = 100
X_train_pad = pad_sequences(X_train_seq, maxlen=max_length)
X_test_pad = pad_sequences(X_test_seq, maxlen=max_length)

model = Sequential()

model.add(Embedding(input_dim=vocab_size, output_dim=32, input_length=max_length))
model.add(SimpleRNN(32, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train_pad, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

loss, accuracy = model.evaluate(X_test_pad, y_test)
print("Test Accuracy:", accuracy)

import numpy as np

def predict_spam(message):
    # Tokenize the message
    message_seq = tokenizer.texts_to_sequences([message])
    # Pad the sequence
    message_pad = pad_sequences(message_seq, maxlen=max_length)
    # Predict
    prediction = model.predict(message_pad)[0][0]

    # Interpret the prediction
    if prediction > 0.5:
        label = encoder.inverse_transform([1])[0] # Assuming 1 is 'spam'
        confidence = prediction * 100
    else:
        label = encoder.inverse_transform([0])[0] # Assuming 0 is 'ham'
        confidence = (1 - prediction) * 100

    return label, confidence

message = input("Enter a message to classify: ")
label, confidence = predict_spam(message)
print(f"Message: '{message}'")
print(f"Prediction: {label} with {confidence:.2f}% confidence")