# -*- coding: utf-8 -*-
"""DL_Expt6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6WVMKv9iFP-zeRVG9tXeJEfc6V32J1K
"""

import pandas as pd
import numpy as np
import re

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, GRU, Dropout
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_json("News_Category_Dataset_v3.json", lines=True)

df = df[['headline', 'category']]

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

df['headline'] = df['headline'].apply(clean_text)
top_categories = df['category'].value_counts().nlargest(10).index
df = df[df['category'].isin(top_categories)]

df = df.sample(12000, random_state=42)
texts = df['headline']
labels = df['category']

encoder = LabelEncoder()
labels = encoder.fit_transform(labels)
tokenizer = Tokenizer(num_words=20000, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

X = pad_sequences(sequences, maxlen=100)
X_train, X_test, y_train, y_test = train_test_split(
    X, labels, test_size=0.2, random_state=42
)
early_stop = EarlyStopping(patience=10, restore_best_weights=True)

model_lstm = Sequential([
    Embedding(20000, 64),
    LSTM(64),
    Dropout(0.4),
    Dense(32, activation='relu'),
    Dense(len(set(labels)), activation='softmax')
])

model_lstm.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

print("\nTraining LSTM Model...\n")

model_lstm.fit(
    X_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.2,
    callbacks=[early_stop]
)

loss_lstm, acc_lstm = model_lstm.evaluate(X_test, y_test)
print("\nLSTM Accuracy:", acc_lstm)

model_gru = Sequential([
    Embedding(20000, 64),
    GRU(64),
    Dropout(0.4),
    Dense(32, activation='relu'),
    Dense(len(set(labels)), activation='softmax')
])

model_gru.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

print("\nTraining GRU Model...\n")

model_gru.fit(
    X_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.2,
    callbacks=[early_stop]
)

# Evaluate
loss_gru, acc_gru = model_gru.evaluate(X_test, y_test)
print("\nGRU Accuracy:", acc_gru)